# Generated by Django 4.2.1 on 2023-06-09 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('ano_letivo_frequentado', models.IntegerField()),
                ('topicos_abordados', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaLinguistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('certificacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaOrganizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('logotipo_instituicao', models.ImageField(upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteresseHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('fotografia', models.ImageField(upload_to='interesses_hobbies')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OutrasHabilitacoees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_criacao', models.IntegerField()),
                ('criador', models.CharField(max_length=100)),
                ('logotipo', models.ImageField(upload_to='logotipos_tecnologias')),
                ('link_site_oficial', models.URLField()),
                ('linguagens_usadas', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano_realizacao', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='tfc')),
                ('resumo', models.TextField()),
                ('link_relatorio', models.URLField()),
                ('link_repositorio', models.URLField()),
                ('link_video', models.URLField()),
                ('autores', models.ManyToManyField(related_name='tfc_autores', to='portfolio.pessoa')),
                ('orientadores', models.ManyToManyField(related_name='tfc_orientadores', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pagina')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='projetos')),
                ('ano_realizacao', models.IntegerField()),
                ('link_repositorio', models.URLField()),
                ('link_video', models.URLField()),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira')),
                ('participantes', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.secao')),
            ],
        ),
    ]
