# Generated by Django 4.2.1 on 2023-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cadeira_certificado_competencialinguistica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosExtraidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
