# Generated by Django 4.2.1 on 2023-06-15 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_dadosextraidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosextraidos',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
