# Generated by Django 4.2.1 on 2023-06-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_dadosextraidos_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteresseHobby',
        ),
    ]
