# Generated by Django 4.2.1 on 2023-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_question_alter_educacao_logotipo_instituicao_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CompetenciaLinguistica',
        ),
        migrations.DeleteModel(
            name='CompetenciaOrganizativa',
        ),
        migrations.DeleteModel(
            name='CompetenciaPessoal',
        ),
        migrations.DeleteModel(
            name='CompetenciaSocial',
        ),
        migrations.DeleteModel(
            name='CompetenciaTecnica',
        ),
    ]
