# Generated by Django 4.2.1 on 2023-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='DadosExtraidos',
        ),
        migrations.AlterField(
            model_name='cidade',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
