# Generated by Django 4.2.1 on 2023-10-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_choice_question_delete_dadosextraidos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutrasHabilitacoees',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(default='static/portfolio/images/image default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificadoImage',
            field=models.ImageField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
